from __future__ import annotations

import re

import pandas as pd

from manpower_app.utils import normalize_lookup_text


ACTIVITY_MAPPING = {
    'Production': 'Factory',
    'Mgic Store': 'Showroom',
    'Logistics': 'Installation',
    'Maintenance': 'Factory',
    'Idle Saudi Labor': 'Idle Saudi Labor',
    'Accounts': 'Head Office',
    'Administration': 'Head Office',
    'Head Office': 'Head Office',
    'Procurement': 'Head Office',
    'Marketing': 'Head Office',
    'Cost controll': 'Head Office',
    'Planning': 'Head Office',
    'Contracting': 'Installation',
    'Quarries': 'Quarries',
    'AD.F - VIP South Land': 'Installation',
    'Shamiya Makkah Haram Extension -Piazza P1150': 'Installation',
    'Shamiya Service Buildings Deck': 'Installation',
    'OBEROI HOTEL Riyad': 'Installation',
    'Shopdrawing': 'Head Office',
    'MATAF EXTENSION': 'Installation',
    'KSAU - HS - Mental Health Hospital': 'Installation',
    'Shura Central Hotel 01 - Stone Surfaces': 'Installation',
    'Shura Central Hotel 01 – Stone Surfaces': 'Installation',
    'CUC Tunnels': 'Installation',
    'King Faisal Specialist Hospital Project - Jeddah': 'Installation',
    'Al-Khaldiyah Palace': 'Installation',
    'KSAU - HS - Administration Building': 'Installation',
    'HARAM HIGH SPEED RAIL (Makkah Station)': 'Installation',
    'Al Murjan Villa': 'Installation',
    'Installation Supply': 'Installation',
    'Jeddah Showroom': 'Showroom',
    'MAC - Laheq Sales Center': 'Installation',
    'INTERGRATIVE WELLNESS core-30859030301': 'Installation',
    'MGIC - Laheq Sales Center': 'Installation',
    'Showroom': 'Showroom',
    'Export': 'Head Office',
}

NORMALIZED_ACTIVITY_MAPPING = {
    normalize_lookup_text(key): value for key, value in ACTIVITY_MAPPING.items()
}

PROFESSION_MAPPING = {
    'Executive Management': 'Executive Management',
    'Operator': 'Operator',
    'Officer': 'Officer',
    'Foreman': 'Foreman',
    'Super-Intendant': 'Superintendent',
    'Labor': 'Labor',
    'Inspector': 'Inspector',
    'Skilled Labor': 'Skilled Labor',
    'Coordinator': 'Coordinator',
    'Controller': 'Controller',
    'Supervisor': 'Supervisor',
    'Purchaser': 'Purchaser',
    'Clerk': 'Clerk',
    'Document Controller': 'Controller',
    'Technician': 'Technician',
    'Driver': 'Driver',
    'Manager': 'Manager',
    'Assistant': 'Assistant',
    'Engineer': 'Engineer',
    'Analyst': 'Analyst',
    'Store Keeper': 'Store Keeper',
    'Messenger': 'Messenger',
    'Surveyor': 'Surveyor',
    'Representative': 'Representative',
    'Draftsman': 'Draftsman',
    'Time Keeper': 'Time Keeper',
    'Treasurer': 'Treasurer',
    'Specialist': 'Administration',
    'Accountant': 'Administration',
    'Administrator': 'Administration',
    'Cashier': 'Administration',
    'Security Guard': 'Security Guard',
    'Senior Geologist': 'Geologist',
    'Geologist': 'Geologist',
    'Junior Technician': 'Technician',
    'Marble Finishing Technician': 'Technician',
    'Marble Installation Technician': 'Technician',
    'Semi Skilled Labor': 'Skilled Labor',
    'Junior Foreman': 'Foreman',
    'Installation Foreman': 'Foreman',
    'Junior Surveyor': 'Surveyor',
    'Quality Inspector': 'Inspector',
    'Maintenance Technician': 'Technician',
    'Machine Operator': 'Operator',
    'Junior Operator': 'Operator',
    'Senior Technician': 'Technician',
    'Junior Inspector': 'Inspector',
    'Junior Clerk': 'Clerk',
    'Junior Engineer': 'Engineer',
    'Senior Operator': 'Operator',
    'Drill Technician': 'Technician',
    'Finisher': 'Finisher',
    'Fixer': 'Skilled Labor',
    'Labor Polishing': 'Skilled Labor',
    'Support': 'Labor',
    'Scissor Operator': 'Operator',
    'Labor Grouting': 'Skilled Labor',
    'Labor Safety': 'Labor',
    'Night Security Guard': 'Security Guard',
    'Polisher': 'Skilled Labor',
    'Camp Labor': 'Labor',
    'Forklift Operator': 'Operator',
    'Store Labor': 'Labor',
    'SAFETY FOREMAN': 'Foreman',
    'Electrician Labor': 'Labor',
    'Safety': 'Safety Officer',
    'Welder Operator': 'Technical Operator',
    'MARBLE FIXER': 'Skilled Labor',
    'Asst.Timekeeper': 'Time Keeper',
    'ASST. TIMEKEEPER': 'Time Keeper',
    'Motor Rewinding': 'Skilled Labor',
    'Electrician': 'Skilled Labor',
    'MECHANIC': 'Skilled Labor',
    'LATHEMACHINE OPERATOR': 'Technical Operator',
    'WELDER': 'Skilled Labor',
    'INDUSTRIAL MECHANIC': 'Skilled Labor',
    'PRODUCTION FOREMAN': 'Foreman',
    'Driller': 'Skilled Labor',
    'EQUIPMENT OPERATOR': 'Operator',
    'DATA ENTRY': 'Administration',
    'MECHANICAL ENGINEER': 'Engineer',
    'SPARE PARTS FOREMAN': 'Foreman',
    'TECHNICAL DATA OPERATOR': 'Technical Operator',
    'Lathe machine': 'Technical Operator',
    'Heavy equipment operator': 'Technical Operator',
    'SALES REPRESENTATIVE': 'Representative',
    'Erector': 'Skilled Labor',
    'Help': 'Labor',
    'MARBLE FINISHER': 'Finisher',
    'Support Foreman': 'Foreman',
    'Safety/Security': 'Security Guard',
    'Camp/Security': 'Security Guard',
    'Grouting Labor': 'Labor',
    'Office Boy': 'Labor',
    'Timekeeper': 'Time Keeper',
    'Finishing Foreman': 'Foreman',
    'QUARRIES SUPVERSIOR': 'Supervisor',
    'SAFETY OFFICER': 'Safety Officer',
    'Forklift opp.': 'Operator',
    'PAINTER': 'Skilled Labor',
    'MATERIAL PLANNING MANAGER': 'Management',
    'Procurement Agent': 'Administration',
    'PROJECT ENGINEER (Planing)': 'Engineer',
    'QUALITY CONTROL COORDINATOR': 'Administration',
    'Gang Leader': 'Foreman',
    'Quarry Worker': 'Skilled Labor',
    'Water Treatment  Operator': 'Technical Operator',
    'INDUSTRIAL TECHNICAL': 'Technician',
    'Site/Security': 'Security Guard',
    'Mechanical': 'Skilled Labor',
    'Bobcat Operator': 'Operator',
    'Store Foreman': 'Foreman',
    'Logistic Foreman': 'Foreman',
    'Polishing Foreman': 'Foreman',
    'Project Engineer': 'Engineer',
    'ESTIMATION BIM ENGINEER': 'Engineer',
    'Finish': 'Finisher',
    'Supp': 'Superintendent',
    'Technical Manager': 'Management',
    'Carpenter': 'Skilled Labor',
    'Quantity Surveyor': 'Surveyor',
    'S Labor': 'Skilled Labor',
}

NORMALIZED_PROFESSION_MAPPING = {
    normalize_lookup_text(key): value for key, value in PROFESSION_MAPPING.items()
}

JOB_FAMILY_MAPPING = {
    'Factory - Executive Management': 'Executive Management',
    'Factory - Operator': 'Factory Operator',
    'Showroom - Officer': 'Safety Officer',
    'Installation - Operator': 'Installation Operator',
    'Factory - Foreman': 'Production Foreman',
    'Factory - Superintendent': 'Administration',
    'Installation - Officer': 'Safety Officer',
    'Factory - Labor': 'Labor',
    'Factory - Inspector': 'Factory Inspector',
    'Factory - Skilled Labor': 'Skilled Labor',
    'Factory - Coordinator': 'Coordinator',
    'Showroom - Controller': 'Controller',
    'Factory - Supervisor': 'Factory Supervisor',
    'Factory - Purchaser': 'Administration',
    'Factory - Clerk': 'Clerk',
    'Factory - Controller': 'Controller',
    'Factory - Technician': 'Technician',
    'Installation - Driver': 'Driver',
    'Factory - Officer': 'Safety Officer',
    'Idle Saudi Labor - Operator': 'Installation Operator',
    'Showroom - Operator': 'Factory Operator',
    'Installation - Labor': 'Labor',
    'Showroom - Labor': 'Labor',
    'Factory - Manager': 'Management',
    'Factory - Assistant': 'Assistant',
    'Factory - Engineer': 'Engineer',
    'Factory - Analyst': 'Analyst',
    'Installation - Supervisor': 'Installation Supervisor',
    'Showroom - Store Keeper': 'Store Keeper',
    'Idle Saudi Labor - Messenger': 'Labor',
    'Idle Saudi Labor - Technician': 'Technician',
    'Idle Saudi Labor - Officer': 'Safety Officer',
    'Showroom - Clerk': 'Clerk',
    'Idle Saudi Labor - Skilled Labor': 'Idle Saudi Skilled Labor',
    'Factory - Surveyor': 'Surveyor',
    'Idle Saudi Labor - Representative': 'Representative',
    'Factory - Draftsman': 'Draftsman',
    'Showroom - Coordinator': 'Coordinator',
    'Installation - Controller': 'Controller',
    'Idle Saudi Labor - Purchaser': 'Administration',
    'Showroom - Foreman': 'Production Foreman',
    'Idle Saudi Labor - Clerk': 'Clerk',
    'Factory - Driver': 'Driver',
    'Factory - Time Keeper': 'Time Keeper',
    'Installation - Engineer': 'Engineer',
    'Showroom - Manager': 'Management',
    'Head Office - Manager': 'Management',
    'Head Office - Clerk': 'Clerk',
    'Head Office - Treasurer': 'Administration',
    'Head Office - Skilled Labor': 'Skilled Labor',
    'Head Office - Labor': 'Labor',
    'Head Office - Foreman': 'Installation Foreman',
    'Head Office - Coordinator': 'Coordinator',
    'Head Office - Messenger': 'Labor',
    'Head Office - Purchaser': 'Administration',
    'Head Office - Analyst': 'Analyst',
    'Head Office - Controller': 'Controller',
    'Head Office - Engineer': 'Engineer',
    'Head Office - Supervisor': 'Installation Supervisor',
    'Head Office - Surveyor': 'Surveyor',
    'Head Office - Executive Management': 'Executive Management',
    'Head Office - Officer': 'Safety Officer',
    'Head Office - Assistant': 'Assistant',
    'Installation - Manager': 'Management',
    'Head Office - Driver': 'Driver',
    'Head Office - Draftsman': 'Draftsman',
    'Quarries - Supervisor': 'Quarries Supervisor',
    'Quarries - Technician': 'Technician',
    'Quarries - Foreman': 'Quarries Foreman',
    'Quarries - Security Guard': 'Security Guard',
    'Quarries - Clerk': 'Clerk',
    'Quarries - Messenger': 'Labor',
    'Quarries - Store Keeper': 'Store Keeper',
    'Quarries - Operator': 'Quarries Operator',
    'Quarries - Driver': 'Driver',
    'Quarries - Geologist': 'Geologist',
    'Quarries - Officer': 'Safety Officer',
    'Quarries - Manager': 'Management',
    'Installation - Foreman': 'Installation Foreman',
    'Installation - Executive Management': 'Executive Management',
    'Installation - Purchaser': 'Administration',
    'Installation - Technician': 'Technician',
    'Installation - Clerk': 'Clerk',
    'Installation - Skilled Labor': 'Skilled Labor',
    'Installation - Messenger': 'Labor',
    'Installation - Store Keeper': 'Store Keeper',
    'Installation - Coordinator': 'Coordinator',
    'Installation - Surveyor': 'Surveyor',
    'Installation - Analyst': 'Analyst',
    'Installation - Draftsman': 'Draftsman',
    'Showroom - Driver': 'Driver',
    'Showroom - Technician': 'Technician',
    'Installation - Time Keeper': 'Time Keeper',
    'Installation - Assistant': 'Assistant',
    'Installation - Inspector': 'Installation Inspector',
    'Installation - Superintendent': 'Administration',
    'Head Office - Inspector': 'Installation Inspector',
    'Showroom - Supervisor': 'Showroom Supervisor',
    'Showroom - Inspector': 'Factory Inspector',
    'Showroom - Engineer': 'Engineer',
    'Showroom - Draftsman': 'Draftsman',
    'Showroom - Surveyor': 'Surveyor',
    'Showroom - Representative': 'Representative',
    'Showroom - Skilled Labor': 'Skilled Labor',
    'Factory  - Labor': 'Labor',
    'Factory  - Technician': 'Technician',
    'Factory  - Operator': 'Factory Operator',
    'Factory  - Inspector': 'Factory Inspector',
    'Factory  - Clerk': 'Clerk',
    'Factory  - Coordinator': 'Coordinator',
    'Factory  - Controller': 'Controller',
    'Factory  - Driver': 'Driver',
    'Factory  - Engineer': 'Engineer',
    'Factory  - Foreman': 'Production Foreman',
    'Quarries - Coordinator': 'Coordinator',
    'Installation - Finisher': 'Installation Finisher',
    'Installation - Security Guard': 'Security Guard',
    'Installation - Safety Officer': 'Safety Officer',
    'Installation - Technical Operator': 'Installation Technical Operator',
    'Factory  - Finisher': 'Factory Finisher',
    'Factory  - Skilled Labor': 'Skilled Labor',
    'Factory  - Store Keeper': 'Store Keeper',
    'Factory  - Technical Operator': 'Factory Technical Operator',
    'Quarries - Skilled Labor': 'Skilled Labor',
    'Head Office - Administration': 'Administration',
    'Installation - Administration': 'Administration',
    'Showroom - Administration': 'Administration',
    'Factory  - Administration': 'Administration',
    'Factory  - Management': 'Management',
    'Installation - Management': 'Management',
    'Quarries - Technical Operator': 'Quarries Technical Operator',
    'Factory  - Safety Officer': 'Safety Officer',
    'Factory  - Supervisor': 'Factory Supervisor',
    'Head Office - Operator': 'Installation Operator',
    'Quarries - Engineer': 'Engineer',
    'Installation - Driver': 'Driver',
    'Installation - Foreman': 'Installation Foreman',
    'Installation - Skilled Labor': 'Skilled Labor',
    'Installation - Technician': 'Technician',
    'Installation - Labor': 'Labor',
    'Installation - Store Keeper': 'Store Keeper',
    'Installation - Engineer': 'Engineer',
    'Installation - Operator': 'Installation Operator',
    'Installation - Coordinator': 'Coordinator',
}

NORMALIZED_JOB_FAMILY_MAPPING = {
    normalize_lookup_text(re.sub(r"\s*-\s*", " - ", key)): value
    for key, value in JOB_FAMILY_MAPPING.items()
}

TOTAL_CONFIGURED_JOB_FAMILIES = len(set(JOB_FAMILY_MAPPING.values()))


def get_job_family_with_fallback(activity_profession, exact_mapping):
    """
    Map standardized Activity-Profession to a job family using the embedded mapping only.
    Returns pd.NA when no exact mapping is found.
    """
    if pd.isna(activity_profession) or not isinstance(activity_profession, str):
        return pd.NA

    normalized_exact_mapping = NORMALIZED_JOB_FAMILY_MAPPING

    if activity_profession in exact_mapping:
        return exact_mapping[activity_profession]

    normalized_key = re.sub(r"\s*-\s*", " - ", activity_profession.strip())
    return normalized_exact_mapping.get(normalize_lookup_text(normalized_key), pd.NA)
